baseURL = "https://aucklandmuseum.github.io/human-interface-guidelines/"
languageCode = "en-us"
title = "Auckland Museum"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

publishDir = "docs"

[params]
    logo = "images/logo2.png"

    permalink = "#"

    # Custom assets
    custom_css = ["stylesheets/custom.css"]
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "museum-black"
        accent  = "museum-grey"

    [params.font]
        text = "Roboto"
        code = "Roboto Mono"


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true


[[menu.main]]
    name   = "Digital Experience Design Principles"
    url    = "digital-experience-design-principles/"
    weight = 10

[[menu.main]]
    name   = "Visual Design Foundations"
    url    = "visual-design-foundations/"
    weight = 20

[[menu.main]]
    name   = "UX and UI Guidelines"
    url    = "ux-and-ui-guidelines/"
    weight = 30

[[menu.main]]
    name   = "Analytics"
    url    = "analytics/"
    weight = 40

[[menu.main]]
    name   = "Inclusive Design"
    url    = "inclusive-design/"
    weight = 50

 [[menu.main]]
    name   = "Auckland Museum Assets"
    url    = "auckland-museum-assets/"
    weight = 60

