baseURL = "http://example.org/"
languageCode = "en-us"
title = "Human Interface Guidelines"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    # General information
    # author = "Digitalcraftsman"
    # description = "A material design theme for documentations."
    # copyright = "Released under the MIT license"

    # Repository
    # provider = "GitHub"
    # repo_url = "<github>"

    # version = "1.0.0"
    logo = "images/logo.png"
    # favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "blue-grey"
        accent  = "teal"

    [params.font]
        text = "Roboto"
        code = "Roboto Mono"


[social]
    # twitter = ""
    # github  = "digitalcraftsman"
    # email   = "hello@email.com"

# [[menu.main]]
#    name   = "Material"
#    url    = "/"
#    weight = 0

# [[menu.main]]
#     name   = "Getting started"
#     url    = "getting-started/"
#     weight = 10

# [[menu.main]]
#     name   = "Adding content"
#     url    = "adding-content/"
#     weight = 20

# [[menu.main]]
#     name   = "Roadmap"
#     url    = "roadmap/"
#     weight = 30

# [[menu.main]]
#     name   = "License"
#     url    = "license/"
#     weight = 40


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true


[[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1

[[menu.main]]
    name   = "Introduction"
    url    = "introduction/"
    weight = 10      

[[menu.main]]
    name   = "Digital Experience Design Principals"
    url    = "digital-experience-design-principals/"
    weight = 20      

[[menu.main]]
    name   = "Visual Design Foundations"
    url    = "visual-design-foundations/"
    weight = 30      

[[menu.main]]
    name   = "UX and UI Guidelines"
    url    = "ux-and-ui-guidelines/"
    weight = 40      

[[menu.main]]
    name   = "UI Text"
    url    = "ui-text/"
    weight = 50

[[menu.main]]
    name   = "Inclusive Design"
    url    = "inclusive-design/"
    weight = 60 

[[menu.main]]
    name   = "Platforms"
    url    = "platforms/"
    weight = 70 
 
 [[menu.main]]
    name   = "Auckland Museum Assets"
    url    = "auckland-museum-assets/"
    weight = 80 
 
